Added new module "pylint-exit" which allows the workflow to only fail on fatal error.

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -19,7 +19,7 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install flake8 pytest pylint
+          pip install flake8 pytest pylint pylint-exit
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
       - name: Lint with flake8
         run: |
@@ -29,7 +29,8 @@ jobs:
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
       - name: Lint with PyLint
         run: |
-          pylint $(git ls-files '*.py'); if [ $(( $? & 2 )) -eq 2 ]; then exit 1; else exit 0; fi
+          pylint $(git ls-files '*.py') || pylint-exit $?
+          # Allows pylint to exit "gracefully" meaning we will only fail build if we get a fatal error. 
       - name: Test with pytest
         run: |
           pytest
